"""Add message id to income balance

Revision ID: 362fd690ef66
Revises: 66efcf6bdf3c
Create Date: 2025-06-24 12:31:41.462377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '362fd690ef66'
down_revision: Union[str, Sequence[str], None] = '66efcf6bdf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_balance', sa.Column('message_id', sa.BigInteger(), nullable=False))   
    op.add_column('income_balance', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('income_balance', sa.Column('trx_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('income_balance', 'message_id')
    op.drop_column('income_balance', 'message')
    op.drop_column('income_balance', 'trx_id')