"""add_private_bot_group_binding_table

Revision ID: e57afc3050d6
Revises: 2s8arzppm5da
Create Date: 2025-07-27 14:42:11.504985+07:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e57afc3050d6'
down_revision: Union[str, Sequence[str], None] = '2s8arzppm5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('identifier', table_name='users')
    op.drop_index('phone_number', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.drop_table('shifts')
    op.drop_index('uq_group_package_chat_group_id', table_name='group_package')
    op.drop_table('group_package')
    op.drop_index('chat_id', table_name='chat_group')
    op.drop_table('chat_group')
    op.drop_table('bot_questions')
    op.drop_index('chat_id', table_name='shift_configurations')
    op.drop_table('shift_configurations')
    op.drop_index('idx_income_chat_date', table_name='income_balance')
    op.drop_index('idx_income_chat_id', table_name='income_balance')
    op.drop_index('idx_income_date', table_name='income_balance')
    op.drop_table('income_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_balance',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('chat_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('original_amount', mysql.FLOAT(), nullable=False),
    sa.Column('income_date', mysql.DATETIME(), nullable=False),
    sa.Column('message_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_shift', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_shift_closed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('trx_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('sent_by', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='income_balance_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_income_date', 'income_balance', ['income_date'], unique=False)
    op.create_index('idx_income_chat_id', 'income_balance', ['chat_id'], unique=False)
    op.create_index('idx_income_chat_date', 'income_balance', ['chat_id'], unique=False)
    op.create_table('shift_configurations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('auto_close_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('shift_name_prefix', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('reset_numbering_daily', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('timezone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('auto_close_times', mysql.TEXT(), nullable=True),
    sa.Column('last_job_run', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('chat_id', 'shift_configurations', ['chat_id'], unique=False)
    op.create_table('bot_questions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_type', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('is_replied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('context_data', mysql.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chat_group',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('enable_shift', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_group_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('chat_id', 'chat_group', ['chat_id'], unique=False)
    op.create_table('group_package',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package', mysql.ENUM('TRIAL', 'FREE', 'BASIC', 'STANDARD', 'BUSINESS'), server_default=sa.text("'TRIAL'"), nullable=False),
    sa.Column('is_paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('package_start_date', mysql.DATETIME(), nullable=True),
    sa.Column('package_end_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_paid_date', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('amount_paid', mysql.FLOAT(), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['chat_group_id'], ['chat_group.id'], name='fk_group_package_chat_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_group_package_chat_group_id', 'group_package', ['chat_group_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('shift_date', sa.DATE(), nullable=False),
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('is_closed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('identifier', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('package', mysql.ENUM('BASIC', 'PRO', 'UNLIMITED'), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=False)
    op.create_index('phone_number', 'users', ['phone_number'], unique=False)
    op.create_index('identifier', 'users', ['identifier'], unique=False)
    # ### end Alembic commands ###
