"""Add shifts table and update income_balance with shift_id

Revision ID: f046bce03312
Revises: 03_modify_name_fields
Create Date: 2025-07-09 07:40:19.583209+07:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f046bce03312'
down_revision: Union[str, Sequence[str], None] = '03_modify_name_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_balance')
    op.drop_index('identifier', table_name='users')
    op.drop_index('phone_number', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.drop_index('chat_id', table_name='chats')
    op.drop_table('chats')
    op.drop_table('chat')
    op.drop_table('bot_questions')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_await_for_reply', mysql.BIT(length=1), nullable=False),
    sa.Column('is_replied', mysql.BIT(length=1), nullable=False),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bot_questions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_type', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('is_replied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('context_data', mysql.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chat',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('from_sender', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chats',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('enable_shift', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('chat_id', 'chats', ['chat_id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('identifier', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('package', mysql.ENUM('BASIC', 'PRO', 'UNLIMITED'), server_default=sa.text("'BASIC'"), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=False)
    op.create_index('phone_number', 'users', ['phone_number'], unique=False)
    op.create_index('identifier', 'users', ['identifier'], unique=False)
    op.create_table('income_balance',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('chat_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('income_date', sa.DATE(), nullable=True),
    sa.Column('original_amount', mysql.FLOAT(), nullable=False),
    sa.Column('message_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('trx_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('shift', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shift_closed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
